### ISSUE TITLE
Error at the Blueprint while uploading data

### ISSUE THREAD

**Issue by diegofrances** [dvandonkelaar/home-assistant-blueprints#8]
Hello,

I have been trying to upload some data but I am receiving errors all time.

One of the first errors that I have received is that WUnderground is expecting data in Imperial and my device does no generate it in imperial.

Due to the above, I have been forced to create a template that converts the sensor to return the data in imperial but unfortunately the blueprint does not recognize those new sensors so cannot be selected and I get error when I trigger the automation.

Error Log:

Registrador: homeassistant.components.rest_command
Fuente: components/rest_command/__init__.py:173
integración: RESTful Command (documentación, problemas)
Ocurrió por primera vez: 14:03:34 (4 ocurrencias)
Última vez registrado: 14:35:55

Error. Url: https://weatherstation.wunderground.com/weatherstation/updateweatherstation.php?ID=&PASSWORD=&dateutc=now&tempf=&dewptf=&baromin=&action=updateraw. Status code 400. Payload: None

Any further detail, please request and happily I will share.

**Comment by dvandonkelaar** [comment]
Hi, I see the URL has no data in it. `tempf` and `baromin` are empty.
Can you share the YAML of the automation? (you can remove the ID and password for your wetherstation, that info not needed)

**Comment by diegofrances** [comment]
Hello,

I have created all from scratch as I always test everything on my Dev HA. Please find the automation created on my Production HA.

```YAML
alias: WUnderground upload automation
description: ""
use_blueprint:
  path: dvandonkelaar/wunderground_upload.yaml
  input:
    trigger_entities:
      - sensor.aemet_temperature
    station_id: ******
    station_key: ******
    sensor_baro: sensor.iontin24_pressure
    sensor_temp: sensor.aemet_temperature
    sensor_rain: sensor.aemet_rain
    sensor_indoortemp: sensor.sensor_temperatura_humedad_comedor_temperature
    sensor_indoorhumidity: sensor.sensor_temperatura_humedad_comedor_humidity
    refresh_frequency: 30
    curl_command_service: rest_command.upload_to_wunderground
```

This is the error after triggering the created Automation manually:

```
Registrador: homeassistant.components.rest_command
Fuente: components/rest_command/__init__.py:173
integración: RESTful Command (documentación, problemas)
Ocurrió por primera vez: 16:37:16 (1 ocurrencia)
Última vez registrado: 16:37:16

Error. Url: https://weatherstation.wunderground.com/weatherstation/updateweatherstation.php?ID=&PASSWORD=&dateutc=now&tempf=&humidity=&baromin=&dewptf=&rainin=&dailyrainin=&action=updateraw. Status code 400. Payload: None
```

And this is the Rest that I have created:

```YAML
rest_command:
  upload_to_wunderground:
    url: "https://weatherstation.wunderground.com/weatherstation/updateweatherstation.php?ID={{ station_id }}&PASSWORD={{ station_key }}&dateutc=now&tempf={{ sensor_temp }}&humidity={{ sensor_indoorhumidity }}&baromin={{ sensor_baro }}&dewptf=&rainin={{ sensor_rain }}&dailyrainin={{ sensor_rain }}&action=updateraw"
    method: GET
```

Please let me know if you need anything else from my side.

Thank you in advance.

Regards

**Comment by dvandonkelaar** [comment]
Hmm, it seems the sensors are filled in but the output is empty. That should not happen.

Can you output the info in the variables tab in trace of the automation?
(please don't forget to remove the `station_id` and `station_key`

And please use code-tags to make it more readable. I edited your reply and added code-tags.

**Comment by diegofrances** [comment]
Hello,

Thank you for your reply and sorry about the format. Please find more errors:
```
Registrador: homeassistant.helpers.template
Fuente: helpers/template.py:2947
Ocurrió por primera vez: 07:27:23 (14 ocurrencias)
Última vez registrado: 07:30:24

Template variable warning: 'station_key' is undefined when rendering 'https://weatherstation.wunderground.com/weatherstation/updateweatherstation.php?ID={{ station_id }}&PASSWORD={{ station_key }}&dateutc=now&tempf={{ sensor_temp }}&humidity={{ sensor_indoorhumidity }}&baromin={{ sensor_baro }}&dewptf=&rainin={{ sensor_rain }}&dailyrainin={{ sensor_rain }}&action=updateraw'
Template variable warning: 'sensor_temp' is undefined when rendering 'https://weatherstation.wunderground.com/weatherstation/updateweatherstation.php?ID={{ station_id }}&PASSWORD={{ station_key }}&dateutc=now&tempf={{ sensor_temp }}&humidity={{ sensor_indoorhumidity }}&baromin={{ sensor_baro }}&dewptf=&rainin={{ sensor_rain }}&dailyrainin={{ sensor_rain }}&action=updateraw'
Template variable warning: 'sensor_indoorhumidity' is undefined when rendering 'https://weatherstation.wunderground.com/weatherstation/updateweatherstation.php?ID={{ station_id }}&PASSWORD={{ station_key }}&dateutc=now&tempf={{ sensor_temp }}&humidity={{ sensor_indoorhumidity }}&baromin={{ sensor_baro }}&dewptf=&rainin={{ sensor_rain }}&dailyrainin={{ sensor_rain }}&action=updateraw'
Template variable warning: 'sensor_baro' is undefined when rendering 'https://weatherstation.wunderground.com/weatherstation/updateweatherstation.php?ID={{ station_id }}&PASSWORD={{ station_key }}&dateutc=now&tempf={{ sensor_temp }}&humidity={{ sensor_indoorhumidity }}&baromin={{ sensor_baro }}&dewptf=&rainin={{ sensor_rain }}&dailyrainin={{ sensor_rain }}&action=updateraw'
Template variable warning: 'sensor_rain' is undefined when rendering 'https://weatherstation.wunderground.com/weatherstation/updateweatherstation.php?ID={{ station_id }}&PASSWORD={{ station_key }}&dateutc=now&tempf={{ sensor_temp }}&humidity={{ sensor_indoorhumidity }}&baromin={{ sensor_baro }}&dewptf=&rainin={{ sensor_rain }}&dailyrainin={{ sensor_rain }}&action=updateraw'
``` 


More errors:
```
Registrador: homeassistant.components.rest_command
Fuente: components/rest_command/__init__.py:173
integración: RESTful Command (documentación, problemas)
Ocurrió por primera vez: 07:27:24 (2 ocurrencias)
Última vez registrado: 07:30:25

Error. Url: https://weatherstation.wunderground.com/weatherstation/updateweatherstation.php?ID=&PASSWORD=&dateutc=now&tempf=&humidity=&baromin=&dewptf=&rainin=&dailyrainin=&action=updateraw. Status code 400. Payload: None
``` 

And here is the information I believe you have requested from the automation after triggering it manually:
```YAML
mode: single
max_exceeded: silent
variables:
  station_id: *******
  station_key: *******
  sensor_baro: sensor.iontin24_pressure
  sensor_temp: sensor.aemet_temperature
  sensor_dewpt: ''
  calculate_dewpt: true
  sensor_humidity: ''
  sensor_windspeed: ''
  sensor_windgust: ''
  sensor_winddir: ''
  sensor_windgustdir: ''
  sensor_rain: sensor.aemet_rain
  sensor_dailyrain: ''
  sensor_indoortemp: sensor.sensor_temperatura_humedad_comedor_temperature
  sensor_indoorhumidity: sensor.sensor_temperatura_humedad_comedor_humidity
  sensor_solarradiation: ''
  sensor_UV: ''
  rtfreq: 30
  delay: 10
  baromin: >
    {% set unit_of_measurement = state_attr(sensor_baro, 'unit_of_measurement')
    %} {{ sensor_baro if sensor_baro == ''
        else (states(sensor_baro) | float(default=0)) if unit_of_measurement not in ['mbar', 'hPa']
          else ((states(sensor_baro) | float(default=0)) / 33.8639) }}
  tempf: >
    {% set unit_of_measurement = state_attr(sensor_temp, 'unit_of_measurement')
    %} {{ sensor_temp if sensor_temp == ''
        else ((states(sensor_temp) | float(default=0)) if unit_of_measurement == '°F'
          else ((states(sensor_temp) | float(default=0)) * 1.8) + 32) }}
  humidity: >
    {{ sensor_humidity if sensor_humidity == '' else (states(sensor_humidity) |
    float(default=0)) }}
  windspeedmph: >
    {% set unit_of_measurement = state_attr(sensor_windspeed,
    'unit_of_measurement') %} {{ sensor_windspeed if sensor_windspeed == ''
        else (states(sensor_windspeed) | float(default=0)) * (0.6213 if unit_of_measurement == 'km/h' else 1) }}
  windgustmph: >
    {% set unit_of_measurement = state_attr(sensor_windgust,
    'unit_of_measurement') %} {{ sensor_windgust if sensor_windgust == ''
        else (states(sensor_windgust) | float(default=0)) * (0.6213 if unit_of_measurement == 'km/h' else 1) }}
  winddir: >
    {% set candidate_wind_direction = states(sensor_winddir) %} {% set
    wind_direction_float = candidate_wind_direction | float(default=-1) %} {% if
    wind_direction_float == -1 %}
      {% set directions_map16 = {'N': 0, 'NNE': 22.5, 'NE': 45, 'ENE': 67.5, 'E': 90, 'ESE': 112.5, 'SE': 135, 'SSE': 157.5, 'S': 180, 'SSW': 202.5, 'SW': 225, 'WSW': 247.5, 'W': 270, 'WNW': 292.5, 'NW': 315, 'NNW': 337.5} %}
      {% set candidate_wind_direction = candidate_wind_direction.upper() %}
      {{ directions_map16.get(candidate_wind_direction, '') | float(default=0) }}
    {%- else -%}
      {{ wind_direction_float }}
    {%- endif %}
  windgustdir: >
    {% set candidate_windgust_direction = states(sensor_windgustdir) %} {% set
    windgust_direction_float = candidate_windgust_direction | float(default=-1)
    %} {% if windgust_direction_float == -1 %}
      {% set directions_map16 = {'N': 0, 'NNE': 22.5, 'NE': 45, 'ENE': 67.5, 'E': 90, 'ESE': 112.5, 'SE': 135, 'SSE': 157.5, 'S': 180, 'SSW': 202.5, 'SW': 225, 'WSW': 247.5, 'W': 270, 'WNW': 292.5, 'NW': 315, 'NNW': 337.5} %}
      {% set candidate_windgust_direction = candidate_windgust_direction.upper() %}
      {{ directions_map16.get(candidate_windgust_direction, '') | float(default=0) }}
    {%- else -%}
      {{ windgust_direction_float }}
    {%- endif %}
  rainin: >
    {% set unit_of_measurement = state_attr(sensor_rain, 'unit_of_measurement')
    %} {{ sensor_rain if sensor_rain == ''
        else ((states(sensor_rain) | float(default=0)) / (25.4 if unit_of_measurement == 'mm' else 1)) }}
  dailyrainin: >
    {% set unit_of_measurement = state_attr(sensor_dailyrain,
    'unit_of_measurement') %} {{ sensor_dailyrain if sensor_dailyrain == ''
        else ((states(sensor_dailyrain) | float(default=0)) / (25.4 if unit_of_measurement == 'mm' else 1)) }}
  indoortempf: >
    {% set unit_of_measurement = state_attr(sensor_indoortemp,
    'unit_of_measurement') %} {{ sensor_indoortemp if sensor_indoortemp == ''
        else ((states(sensor_indoortemp) | float(default=0)) if unit_of_measurement == '°F'
          else ((states(sensor_indoortemp) | float(default=0)) * 1.8) + 32) }}
  indoorhumidity: |
    {{ sensor_indoorhumidity if sensor_indoorhumidity == ''
        else (states(sensor_indoorhumidity) | float(default=0)) }}
  solarradiation: >
    {% set unit_of_measurement = state_attr(sensor_solarradiation,
    'unit_of_measurement') %} {{ sensor_solarradiation if sensor_solarradiation
    == ''
        else ((states(sensor_solarradiation) | float(default=0) / 126.7) ) if unit_of_measurement == 'lux'
          else (states(sensor_solarradiation) | float(default=0)) }}
  UV: |
    {{ sensor_UV if sensor_UV == ''
        else (states(sensor_UV) | int(default=0)) }}
  dewptf_calculated: >
    {% set unit_of_measurement = state_attr(sensor_temp, 'unit_of_measurement')
    %} {% set T = ((states(sensor_temp) | float(default=0)) if
    unit_of_measurement == '°C'
                else ((states(sensor_temp) | float(default=0)) - 32) / 1.8) %}
    {% set RH = humidity %} {% set dewpt = '' %} {% if sensor_temp != '' and
    sensor_humidity != '' %}
      {% set A = log(RH / 100, default=0.0) + (17.62 * T / (243.12 + T)) %}
      {% set dewpt = 243.12 * A / (17.62 - A) %}
      {% set dewpt = (dewpt * 1.8) + 32 %}
    {% endif %} {{ dewpt }}
  dewptf: >
    {% set unit_of_measurement = state_attr(sensor_dewpt, 'unit_of_measurement')
    %} {{ (dewptf_calculated if calculate_dewpt is true
        else sensor_dewpt) if sensor_dewpt == ''
          else ((states(sensor_dewpt) | float(default=0)) if unit_of_measurement == '°F'
            else ((states(sensor_dewpt) | float(default=0)) * 1.8) + 32) }}
  payload: >
    {% set data = namespace(sensors=[]) %}

    {% for i in [['rtfreq', rtfreq]
          ,['baromin', baromin]
          ,['tempf', tempf]
          ,['dewptf', dewptf]
          ,['humidity', humidity]
          ,['windspeedmph', windspeedmph]
          ,['windgustmph', windgustmph]
          ,['winddir', winddir]
          ,['windgustdir', windgustdir]
          ,['rainin', rainin]
          ,['dailyrainin', dailyrainin]
          ,['indoortempf', indoortempf]
          ,['indoorhumidity', indoorhumidity]
          ,['solarradiation', solarradiation]
          ,['UV', UV]
          ]%}
      {% if i[1] != '' %}
        {% set data.sensors = data.sensors + ['{}={}'.format(i[0], (i[1] if i[0] == 'rtfreq'
                                              else (i[1] | round(3)) | string))] %}
      {% endif %}
    {% endfor %}

    {% set _payload = 'ID=' + station_id %} {% set _payload = _payload +
    '&PASSWORD=' + station_key %} {% set _payload = _payload +
    '&action=updateraww' %} {% set _payload = _payload + '&realtime=1' %} {% set
    _payload = _payload + '&dateutc=now' %} {% set _payload = _payload + '&' if
    data.sensors | length > 0 else '' %} {% set _payload = _payload +
    data.sensors | join('&') %} {{ _payload }}
triggers:
  - platform: state
    entity_id:
      - sensor.aemet_temperature
actions:
  - alias: Check if station_id and station_key exist
    if: |
      {{      station_id != ''
          and station_key != ''
      }}
    then:
      - data:
          url: >-
            https://weatherstation.wunderground.com/weatherstation/updateweatherstation.php?{{
            payload }}
        action: rest_command.upload_to_wunderground
  - alias: Wait to prevent multiple uploads
    delay:
      seconds: '{{ delay | int }}'
id: '1749133566049'
alias: WUnderground upload automation
description: ''
``` 

```YAML
id: '1749133566049'
alias: WUnderground upload automation
description: ''
use_blueprint:
  path: dvandonkelaar/wunderground_upload.yaml
  input:
    trigger_entities:
      - sensor.aemet_temperature
    station_id: *****
    station_key: *****
    sensor_baro: sensor.iontin24_pressure
    sensor_temp: sensor.aemet_temperature
    sensor_rain: sensor.aemet_rain
    sensor_indoortemp: sensor.sensor_temperatura_humedad_comedor_temperature
    sensor_indoorhumidity: sensor.sensor_temperatura_humedad_comedor_humidity
    refresh_frequency: 30
    curl_command_service: rest_command.upload_to_wunderground
``` 

Please let me know if you need any further information.

**Comment by dvandonkelaar** [comment]
Hi, thanks but that's not what I mean. The variables tab shows what info is composed from the sensors.

For debugging, the [automation traces](https://www.home-assistant.io/docs/automation/troubleshooting/#traces) has a variables tab showing the variables generated by the automation.
![Image](https://github.com/user-attachments/assets/dde7d703-1564-489e-b1f7-72ef110d81f2)

The YAML above can also be helpful later when we have the variables.

**Comment by diegofrances** [comment]
Hello,

Let's see if this time I am uploading the right data.

```YAML
this:
  entity_id: automation.wunderground_upload_automation
  state: 'on'
  attributes:
    id: 'xxxxxxxxxxxxx'
    last_triggered: '2025-06-22T15:04:50.064637+00:00'
    mode: single
    current: 0
    friendly_name: WUnderground upload automation
  last_changed: '2025-06-16T17:38:06.317124+00:00'
  last_reported: '2025-06-22T15:05:00.533660+00:00'
  last_updated: '2025-06-22T15:05:00.533660+00:00'
  context:
    id: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
    parent_id: null
    user_id: null
trigger:
  id: '0'
  idx: '0'
  alias: null
  platform: state
  entity_id: sensor.aemet_temperature
  from_state:
    entity_id: sensor.aemet_temperature
    state: '37'
    attributes:
      state_class: measurement
      unit_of_measurement: °C
      attribution: Powered by AEMET OpenData
      device_class: temperature
      friendly_name: AEMET Temperature
    last_changed: '2025-06-22T15:04:50.028084+00:00'
    last_reported: '2025-06-22T15:04:50.028084+00:00'
    last_updated: '2025-06-22T15:04:50.028084+00:00'
    context:
      id: xxxxxxxxxxxxxxxxxxxxxxx
      parent_id: null
      user_id: null
  to_state:
    entity_id: sensor.aemet_temperature
    state: '36.8'
    attributes:
      state_class: measurement
      unit_of_measurement: °C
      attribution: Powered by AEMET OpenData
      device_class: temperature
      friendly_name: AEMET Temperature
    last_changed: '2025-06-22T15:34:50.049000+00:00'
    last_reported: '2025-06-22T15:34:50.049000+00:00'
    last_updated: '2025-06-22T15:34:50.049000+00:00'
    context:
      id: xxxxxxxxxxxxxxxxxxxxxxxxxxx
      parent_id: null
      user_id: null
  for: null
  attribute: null
  description: state of sensor.aemet_temperature
station_id: xxxxxxxxxxx
station_key: xxxxxxxxxxxx
sensor_baro: sensor.iontin24_pressure
sensor_temp: sensor.aemet_temperature
sensor_dewpt: ''
calculate_dewpt: true
sensor_humidity: ''
sensor_windspeed: ''
sensor_windgust: ''
sensor_winddir: ''
sensor_windgustdir: ''
sensor_rain: sensor.aemet_rain
sensor_dailyrain: ''
sensor_indoortemp: sensor.sensor_temperatura_humedad_comedor_temperature
sensor_indoorhumidity: sensor.sensor_temperatura_humedad_comedor_humidity
sensor_solarradiation: ''
sensor_UV: ''
rtfreq: 30
delay: 10
baromin: 29.9900483996232
tempf: 98.24
humidity: ''
windspeedmph: ''
windgustmph: ''
winddir: 0
windgustdir: 0
rainin: 0
dailyrainin: ''
indoortempf: 80.42
indoorhumidity: 49
solarradiation: ''
UV: ''
dewptf_calculated: ''
dewptf: ''
payload: >-
  ID=xxxxxxxxxx&PASSWORD=xxxxxxxxxxxxx&action=updateraww&realtime=1&dateutc=now&rtfreq=30&baromin=29.99&tempf=98.24&winddir=0.0&windgustdir=0.0&rainin=0.0&indoortempf=80.42&indoorhumidity=49.0
``` 

Let me know if you need further information.

Regards.

**Comment by dvandonkelaar** [comment]
Strange, the payload seams to suggest the data is sent to WUnderground (`baromin=29.99`, `tempf=98.24`, `winddir=0.0`, `windgustdir=0.0`, `rainin=0.0`, `indoortempf=80.42` and `indoorhumidity=49.0`), which is not the same as the payload in the error.
Is there any data in WUnderground? And is the automation still giving the same error?

Offtopic, I see the value `rtfreq=30`, are your sensors updating every **30 seconds**? Not a problem if so, but it seems quite often for outdoor weather sensors.
WUnderground will render the station offline if there is no measurement after the specified `rtfreq`.

**Comment by diegofrances** [comment]
Hello Dirk,

I've changed the frequency to 900 seconds and I have triggered the automation manually.

This are the errors that I am getting right now:

```YAML
Registrador: homeassistant.helpers.template
Fuente: helpers/template.py:2947
Ocurrió por primera vez: 23 de junio de 2025, 02:08:22 (231 ocurrencias)
Última vez registrado: 16:22:27

Template variable warning: 'station_key' is undefined when rendering 'https://weatherstation.wunderground.com/weatherstation/updateweatherstation.php?ID={{ station_id }}&PASSWORD={{ station_key }}&dateutc=now&tempf={{ sensor_temp }}&humidity={{ sensor_indoorhumidity }}&baromin={{ sensor_baro }}&dewptf=&rainin={{ sensor_rain }}&dailyrainin={{ sensor_rain }}&action=updateraw'
Template variable warning: 'sensor_temp' is undefined when rendering 'https://weatherstation.wunderground.com/weatherstation/updateweatherstation.php?ID={{ station_id }}&PASSWORD={{ station_key }}&dateutc=now&tempf={{ sensor_temp }}&humidity={{ sensor_indoorhumidity }}&baromin={{ sensor_baro }}&dewptf=&rainin={{ sensor_rain }}&dailyrainin={{ sensor_rain }}&action=updateraw'
Template variable warning: 'sensor_indoorhumidity' is undefined when rendering 'https://weatherstation.wunderground.com/weatherstation/updateweatherstation.php?ID={{ station_id }}&PASSWORD={{ station_key }}&dateutc=now&tempf={{ sensor_temp }}&humidity={{ sensor_indoorhumidity }}&baromin={{ sensor_baro }}&dewptf=&rainin={{ sensor_rain }}&dailyrainin={{ sensor_rain }}&action=updateraw'
Template variable warning: 'sensor_baro' is undefined when rendering 'https://weatherstation.wunderground.com/weatherstation/updateweatherstation.php?ID={{ station_id }}&PASSWORD={{ station_key }}&dateutc=now&tempf={{ sensor_temp }}&humidity={{ sensor_indoorhumidity }}&baromin={{ sensor_baro }}&dewptf=&rainin={{ sensor_rain }}&dailyrainin={{ sensor_rain }}&action=updateraw'
Template variable warning: 'sensor_rain' is undefined when rendering 'https://weatherstation.wunderground.com/weatherstation/updateweatherstation.php?ID={{ station_id }}&PASSWORD={{ station_key }}&dateutc=now&tempf={{ sensor_temp }}&humidity={{ sensor_indoorhumidity }}&baromin={{ sensor_baro }}&dewptf=&rainin={{ sensor_rain }}&dailyrainin={{ sensor_rain }}&action=updateraw'
``` 

```YAML
Registrador: homeassistant.components.rest_command
Fuente: components/rest_command/__init__.py:173
integración: RESTful Command (documentación, problemas)
Ocurrió por primera vez: 23 de junio de 2025, 02:08:23 (33 ocurrencias)
Última vez registrado: 16:22:28

Error. Url: https://weatherstation.wunderground.com/weatherstation/updateweatherstation.php?ID=&PASSWORD=&dateutc=now&tempf=&humidity=&baromin=&dewptf=&rainin=&dailyrainin=&action=updateraw. Status code 400. Payload: None
```

This is the variables data in case you might need it again:

```YAML
this:
  entity_id: automation.wunderground_upload_automation
  state: 'on'
  attributes:
    id: 'xxxxxxxxxxxx'
    last_triggered: '2025-06-24T11:36:05.279844+00:00'
    mode: single
    current: 0
    friendly_name: WUnderground upload automation
  last_changed: '2025-06-22T23:28:03.827146+00:00'
  last_reported: '2025-06-24T11:36:15.729438+00:00'
  last_updated: '2025-06-24T11:36:15.729438+00:00'
  context:
    id: xxxxxxxxxxxxxxxxxxxxxxxx
    parent_id: null
    user_id: null
trigger:
  id: '0'
  idx: '0'
  alias: null
  platform: state
  entity_id: sensor.aemet_temperature
  from_state:
    entity_id: sensor.aemet_temperature
    state: '35.3'
    attributes:
      state_class: measurement
      unit_of_measurement: °C
      attribution: Powered by AEMET OpenData
      device_class: temperature
      friendly_name: AEMET Temperature
    last_changed: '2025-06-24T11:36:05.235121+00:00'
    last_reported: '2025-06-24T11:36:05.235121+00:00'
    last_updated: '2025-06-24T11:36:05.235121+00:00'
    context:
      id: xxxxxxxxxxxxxxxxxxxxx
      parent_id: null
      user_id: null
  to_state:
    entity_id: sensor.aemet_temperature
    state: '37'
    attributes:
      state_class: measurement
      unit_of_measurement: °C
      attribution: Powered by AEMET OpenData
      device_class: temperature
      friendly_name: AEMET Temperature
    last_changed: '2025-06-24T14:06:55.573298+00:00'
    last_reported: '2025-06-24T14:06:55.573298+00:00'
    last_updated: '2025-06-24T14:06:55.573298+00:00'
    context:
      id: xxxxxxxxxxxxxxxxxxxxxxxxxxx
      parent_id: null
      user_id: null
  for: null
  attribute: null
  description: state of sensor.aemet_temperature
station_id: xxxxxxxxxxxx
station_key: xxxxxxxxxxxxxx
sensor_baro: sensor.xxxxx_pressure
sensor_temp: sensor.aemet_temperature
sensor_dewpt: ''
calculate_dewpt: true
sensor_humidity: ''
sensor_windspeed: ''
sensor_windgust: ''
sensor_winddir: ''
sensor_windgustdir: ''
sensor_rain: sensor.aemet_rain
sensor_dailyrain: ''
sensor_indoortemp: sensor.sensor_temperatura_humedad_comedor_temperature
sensor_indoorhumidity: sensor.sensor_temperatura_humedad_comedor_humidity
sensor_solarradiation: ''
sensor_UV: ''
rtfreq: 30
delay: 10
baromin: 29.949887638458655
tempf: 98.60000000000001
humidity: ''
windspeedmph: ''
windgustmph: ''
winddir: 0
windgustdir: 0
rainin: 0
dailyrainin: ''
indoortempf: 79.34
indoorhumidity: 45
solarradiation: ''
UV: ''
dewptf_calculated: ''
dewptf: ''
payload: >-  ID=xxxxxx&PASSWORD=xxxxxx&action=updateraww&realtime=1&dateutc=now&rtfreq=30&baromin=29.95&tempf=98.6&winddir=0.0&windgustdir=0.0&rainin=0.0&indoortempf=79.34&indoorhumidity=45.0
```

Thank you in advance.

**Comment by dvandonkelaar** [comment]
Hmm, the `frequency` is changed to `900`, but I see `rtfreq: 30` in de trace. This is strange.
Also, the `payload` seems allright and the log says otherwise.

Since it is a blueprint, could you remove de automation and re-add it?

**Comment by diegofrances** [comment]
Hello Dirk,

I have completed the following process:

1. Automation deleted
2. HA restarted
3. Automation recreated
4. Automation manually triggered

The following errors are seen at the System Logs:
```YAML
Registrador: homeassistant.helpers.template
Fuente: helpers/template.py:2947
Ocurrió por primera vez: 10:24:28 (7 ocurrencias)
Última vez registrado: 10:24:28

Template variable warning: 'station_key' is undefined when rendering 'https://weatherstation.wunderground.com/weatherstation/updateweatherstation.php?ID={{ station_id }}&PASSWORD={{ station_key }}&dateutc=now&tempf={{ sensor_temp }}&humidity={{ sensor_indoorhumidity }}&baromin={{ sensor_baro }}&dewptf=&rainin={{ sensor_rain }}&dailyrainin={{ sensor_rain }}&action=updateraw'
Template variable warning: 'sensor_temp' is undefined when rendering 'https://weatherstation.wunderground.com/weatherstation/updateweatherstation.php?ID={{ station_id }}&PASSWORD={{ station_key }}&dateutc=now&tempf={{ sensor_temp }}&humidity={{ sensor_indoorhumidity }}&baromin={{ sensor_baro }}&dewptf=&rainin={{ sensor_rain }}&dailyrainin={{ sensor_rain }}&action=updateraw'
Template variable warning: 'sensor_indoorhumidity' is undefined when rendering 'https://weatherstation.wunderground.com/weatherstation/updateweatherstation.php?ID={{ station_id }}&PASSWORD={{ station_key }}&dateutc=now&tempf={{ sensor_temp }}&humidity={{ sensor_indoorhumidity }}&baromin={{ sensor_baro }}&dewptf=&rainin={{ sensor_rain }}&dailyrainin={{ sensor_rain }}&action=updateraw'
Template variable warning: 'sensor_baro' is undefined when rendering 'https://weatherstation.wunderground.com/weatherstation/updateweatherstation.php?ID={{ station_id }}&PASSWORD={{ station_key }}&dateutc=now&tempf={{ sensor_temp }}&humidity={{ sensor_indoorhumidity }}&baromin={{ sensor_baro }}&dewptf=&rainin={{ sensor_rain }}&dailyrainin={{ sensor_rain }}&action=updateraw'
Template variable warning: 'sensor_rain' is undefined when rendering 'https://weatherstation.wunderground.com/weatherstation/updateweatherstation.php?ID={{ station_id }}&PASSWORD={{ station_key }}&dateutc=now&tempf={{ sensor_temp }}&humidity={{ sensor_indoorhumidity }}&baromin={{ sensor_baro }}&dewptf=&rainin={{ sensor_rain }}&dailyrainin={{ sensor_rain }}&action=updateraw'
```
```YAML
Registrador: homeassistant.components.rest_command
Fuente: components/rest_command/__init__.py:173
integración: RESTful Command (documentación, problemas)
Ocurrió por primera vez: 10:24:29 (1 ocurrencia)
Última vez registrado: 10:24:29

Error. Url: https://weatherstation.wunderground.com/weatherstation/updateweatherstation.php?ID=&PASSWORD=&dateutc=now&tempf=&humidity=&baromin=&dewptf=&rainin=&dailyrainin=&action=updateraw. Status code 400. Payload: None
```

Find also attached the trace after triggering it manually. I have removed sensible data.

[trace automation.wunderground_upload 2025-06-25T08_24_28.709246+00_00.json](https://github.com/user-attachments/files/20899892/trace.automation.wunderground_upload.2025-06-25T08_24_28.709246%2B00_00.json)

Please, let me know if anything else is required from my side.

Thank you in advance.

**Comment by dvandonkelaar** [comment]
Very strange, since this all should work.

The trace shows the correct URL, with all the values of the different sensors.
```JSON
      "action/0/then/0": [
        {
          "path": "action/0/then/0",
          "timestamp": "2025-06-25T08:24:28.726034+00:00",
          "result": {
            "params": {
              "domain": "rest_command",
              "service": "upload_to_wunderground",
              "service_data": {
                "url": "https://weatherstation.wunderground.com/weatherstation/updateweatherstation.php?ID=xxxxxx&PASSWORD=xxxxxxx&action=updateraww&realtime=1&dateutc=now&rtfreq=900&baromin=29.97&tempf=71.96&dewptf=59.978&humidity=66.0&winddir=0.0&windgustdir=0.0&rainin=0.0&indoortempf=80.06&indoorhumidity=51.0"
              },
              "target": {}
            },
            "running_script": false
          }
        }
      ]
```

What I'm thinking is that the `shel_command` is not working correctly somehow.
Did you create it as shown in the blueprint?
https://github.com/dvandonkelaar/home-assistant-blueprints/blob/12df41b6ce2010951082cc8f0e2d92d67aae6b44/wunderground_upload.yaml#L18-L19

What if you manually run the command with the URL in the trace?
This can be done in `Developer Tools` > `Actions`, by putting in the YAML:
```YAML
action: shell_command.curl_get
data:
    url: https://weatherstation.wunderground.com/weatherstation/updateweatherstation.php?ID=............
```

Just looking at your previous supplied information, I see:
```YAML
curl_command_service: rest_command.upload_to_wunderground
```
So I think it is going wrong here.

**Comment by diegofrances** [comment]
Hello Dirk,

Oh yeah, you are the MAN!! It is working now!! As soon as I have changed the content of "configuration.yaml" to contain the below, it has started working like a charm.

```YAML
############################
#    WUNDERGROUND UPLOAD   #
############################
shell_command:
        curl_get: 'curl -X GET {{ url }}'
```

Thank you for your endless patience and help.

Feel free to mark the issue as resolved.

Best Regards,
Diego
